# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-25 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_register', '0002_contestant'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='ranking_file',
            field=models.FileField(blank=True, upload_to='rankings_txt'),
        ),
    ]
