# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-25 22:40
from __future__ import unicode_literals

import cms_register.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_register', '0003_contest_ranking_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='ranking_url',
        ),
        migrations.AddField(
            model_name='contest',
            name='contest_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='contest',
            name='ranking_file',
            field=models.FileField(blank=True, upload_to=cms_register.models.get_file_path),
        ),
    ]
