# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 10:57
from __future__ import unicode_literals

import cms_register.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_register', '0008_remove_contest_unofficial_ranking_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='unofficial_ranking_file',
            field=models.FileField(blank=True, upload_to=cms_register.models.get_file_path),
        ),
    ]
