# Generated by Django 2.2.6 on 2019-10-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_register', '0009_contest_unofficial_ranking_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
    ]
